name: Build and push to gh-pages branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - name: Set Default Peer Dependencies to true
      run: npm config set legacy-peer-deps true
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: CI= npm run build
    
    - name: Upload production-ready build files
      uses: actions/upload-artifact@v3
      with:
        name: production-files
        path: ./build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: production-files
            path: ./build
        
        - name: Set current date and time as env variable
          run: echo "TIMESTAMP=$(TZ=":US/Eastern" date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV    
    
        - name: Push
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: gh-pages # Branch to push
            FOLDER: build
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MESSAGE: "Auto-Build: ${{ env.TIMESTAMP }} ET"